### ISSUE TITLE
Is it possible to store Firefox (+57) Sync credentials in KeePass?

### ISSUE THREAD

**Issue by jagmoreira** [smorks/keepasshttp-connector#13]
Great work on this fork @smorks, so far it works great on my Firefox Dev Ed 57.

One feature that is missing in your version is the ability to store firefox sync credentials within KeePass.

Is this just not possible with the new WebExtensions paradigm or is something that may come at a later date?

**Comment by sky4055** [comment]
same question here, thanks @jagmoreira !

**Comment by smorks** [comment]
i'm not exactly sure what you mean?

do you mean can you use the credentials stored using the built-in password manager in Firefox (and synced with Firefox Sync) and use those in KeePass? (I believe the old PassIFox used to work like this?)

short answer: no, not that i know of, because of limitations in the new WebExtensions API.

if this isn't what you're asking, then can you please try and clarify for me?

**Comment by jagmoreira** [comment]
> do you mean can you use the credentials stored using the built-in password manager in Firefox (and synced with Firefox Sync) and use those in KeePass? (I believe the old PassIFox used to work like this?)

Correct. For this to work, you had to install PassIFox before setting up Sync. Then, the credentials would be stored in KeePass instead of in firefox's password manager.

From the [old add-on page](https://addons.mozilla.org/en-US/firefox/addon/passifox/):
> Firefox Sync Users:
> * PassIFox should be installed prior to setting up Sync. It will work if you don't, but your sync password and encryption keys will be stored unprotected in firefox (unless you also set a master password for firefox... but why would you want to do that).



>short answer: no, not that i know of, because of limitations in the new WebExtensions API.

That was my suspicion as well.
Still, thanks so much for all the hard work you put into this extension!

**Comment by skorokithakis** [comment]
I actually do both, I have KeePass autofill turned off, but I use it to read and write credentials from/to, and then use Firefox Sync to autofill the forms.
