### ISSUE TITLE
Add FF installation guide to the readme

### ISSUE THREAD

**Issue by skorokithakis** [smorks/keepasshttp-connector#14]
Since FF 57 broke all my extensions, I'm looking for alternatives. As this extension isn't ready yet, I would appreciate some installation instructions for FF 57 from source. Could a short blurb be added to the README?

**Comment by smorks** [comment]
you don't need to install from the source. you should be able to install the xpi on the [releases](https://github.com/smorks/keepasshttp-connector/releases) page.

**Comment by skorokithakis** [comment]
Ah, thanks :/ I thought the Firefox link in the README pointed to the actual browser download. Could it be renamed to "Firefox releases"?

**Comment by smorks** [comment]
i'll change the wording so it's more clear. thanks.
