### ISSUE TITLE
No connection to keepasshttp

### ISSUE THREAD

**Issue by Prophe-T** [smorks/keepasshttp-connector#15]
Hi,
i'm getting an connection error from keepasshttp-connector:
![scr1](https://user-images.githubusercontent.com/10738253/31048794-96ef5646-a625-11e7-903f-a3ca722eedf2.JPG)

Keepasshttp seems to be working properly in KeePass.
The result of netstat -an | select-string "19455" shows:
TCP    0.0.0.0:19455          0.0.0.0:0             listening
TCP    [::]:19455             [::]:0                 listening

System:
Win 10
Connector Version 1.0.0
Firefox 56.0
KeePassHttp version 1.8.4.2
KeePass version 2.36

Greetings
Edit:
Just made shure that it's not keepasshttp: passifox does get a connection to keepasshttp. Unfortunately it does break some websites for me, so i can't use that.

**Comment by smorks** [comment]
i've seen other extensions causing this issue, see #6. try temporarily disabling and proxy/vpn/blocking extensions and see if that helps?

**Comment by Prophe-T** [comment]
So i disabled all of the other extensions, sadly with no effect, still no connection.
![scr2](https://user-images.githubusercontent.com/10738253/31056942-b6ca4db2-a6da-11e7-830b-fdeefc83cb8d.JPG)

If it's useful and you tell me how, i can give you more in depth details.

**Comment by smorks** [comment]
does anything show up when you open localhost:19455? you should get someting like the following, on the network tab:

![localhost](https://user-images.githubusercontent.com/1030007/31058749-53cde4a6-a6be-11e7-91d4-eed311658dd0.png)

rather than an "unable to connect error". if you get unable to connect, try putting in "127.0.0.1:19455" and see if that works too?

if one works and not the other, then maybe try `ping -4 localhost` to make sure that localhost is actually point to 127.0.0.1?

**Comment by Prophe-T** [comment]
Pinging localhost shows that it points to 127.0.0.1 correctly. The network tab shows as follows:
![scr4](https://user-images.githubusercontent.com/10738253/31072654-091ff1c8-a769-11e7-8960-be23aaa27edc.JPG)

**Comment by Prophe-T** [comment]
So i don't know what the issue was. As i said, passifox was able to get a connection to keepasshttp. I wanted to make sure, that the problem isn't on my end, so i did a reset of firefox and added the extensions one by one, keepasshttp-connector first - and it worked. I did not mess with the firefox settings in the first place, so i didn't do that earlier, but it resolved the issue and now the extension works properly, sorry for the hassle.

**Comment by smorks** [comment]
glad you got it working!

**Comment by Prophe-T** [comment]
So today i updated my macbook pro to high sierra. Now keepasshttp-connector does not connect here either. I'm using keepassxc though. I checked my windows machine again and it seems, that the issue is back here too. This is so weird. I got it working for like ten minutes, changed nothing, left the machine for three hours, and its back.

**Comment by smorks** [comment]
are the hostname and port in the Advanced Settings set to the defaults?

and i haven't heard of anyone else having this problem?

**Comment by Prophe-T** [comment]
So i think i found the real issue. I have an addon, which adds buttons to both toggle firefox enable/disable cookies and add a domain to the cookie-whitelist. I'm a bit restrictive about that, so by default, i disable cookies and add sites to the whitelist one by one.
And this is the issue. If i disable cookies, keepasshttp-connector does not get a connection at all. If i enable cookies, it does.
I did not find it on my windows machine, because i did not restart firefox with disabled cookies. But i just confirmed it on my windows and macos machine, both with firefox 56.

Steps to reproduce:
1. In firefox, go to Settings->Security&Pricacy->Disable "Accept cookies"
2. Restart firefox
3. no connection to keepasshttp
4. To restore, enable cookies and restart firefox.

Possible solutions:
1. Enable cookies (but i would prefer to be restrictive here)
2. somehow add keepasshttp-connector to the cookie whitelist (since i don't know how extensions work, i just tried adding the domain from the settings menu. For me it was moz-extension://b16307be-e1e7-9b49-92c9-9e4341b31b42/options/options.html, so i added only the middle part with the quirky numbers and letters, but with no effect)
3. make keepasshttp-connector independent of cookies (don't know if it even is dependent)

**Comment by smorks** [comment]
i didn't think it relied on using cookies, but now that i can reproduce the problem i'll see if i can find a way for it to work when cookies are disabled.

thanks for all your work getting to the root of them problem!

**Comment by Prophe-T** [comment]
Sure, glad i could help and it wasn't a waste of time.

**Comment by smorks** [comment]
it looks like accessing localStorage throws an error when cookies are disabled. i'm only using localStorage for migrating legacy saved prefs, but with the changes in extension id's, there never would be any legacy preferences stored in localStorage.

will remove the logic for that, and it should work with cookies disabled.

**Comment by Prophe-T** [comment]
Sounds great. Thanks for the fix.
