### ISSUE TITLE
Login problems with Google Account

### ISSUE THREAD

**Issue by bones78** [smorks/keepasshttp-connector#19]
I can not access my google-Account with this add-on. https://accounts.google.com/ even if I try to set own credential fields for this page. 
Firefox 56.0
KeePassHttp: 1.8.4.2
KeePassHttp-Connector Version: 1.0.1
Other websites seems to work.

**Comment by smorks** [comment]
i believe this is the same issue as #12. will hopefully have a solution for it soon.

**Comment by sntdavidsc** [comment]
me too on sites like gmail.com paypal.com etc.

**Comment by jreinaldo** [comment]
I have the same problem with Google Accounts (I have more than one). If I set own credential fields it works for username, but not for password, even choosing "Fill pass only". If used, I receive the message: "Unable to find a password field"
Firefox 57.0(64 bits)
KeePassHttp-Connector Version: 1.0.6
KeePassHttp Version: 1.8.4.2
KeePass2 version 2.37
Yahoo mail has different pages for username and password but it works fine. 
Thank you for your work
