### ISSUE TITLE
please dont use  https://passifox.appspot.com/kph/latest-version.txt

### ISSUE THREAD

**Issue by ydf** [smorks/keepasshttp-connector#20]
I cant  connect it， its block at china.

**Comment by ydf** [comment]
#21

**Comment by varjolintu** [comment]
What about just using [https://raw.githubusercontent.com/pfn/keepasshttp/master/latest-version.txt](https://raw.githubusercontent.com/pfn/keepasshttp/master/latest-version.txt)?

**Comment by ydf** [comment]
very good
