### ISSUE TITLE
Autofill HTTP Auth does not work

### ISSUE THREAD

**Issue by aurelg** [smorks/keepasshttp-connector#24]
With `firefox-developer` 57.0b9 (Archlinux, FWIW), HTTP authentication dialogs are not filled anymore despite the checkbox being ticked in the settings page. It is broken since (at least) the previous version, but was working when I first gave a try to `firefox-developer` 57.x together with `keepasshttp-connector` a few weeks before.

**Comment by smorks** [comment]
ack! i broke it! sorry about that! will have this fixed shortly, and will release a new version to AMO & Chrome Web Store.
