### ISSUE TITLE
KeePassHttp-Connector ask access to unwanted password entries

### ISSUE THREAD

**Issue by PlqnctoN** [smorks/keepasshttp-connector#25]
Hi!
So I was searching a solution to an issue a friend had with his laptop when I stumbled accross a certain windows 10 forum. When I opened the webpage, KeePassXC immediatly asked me if I should give the URL access to my PGP Keys password entry as well as my andOTP (a TOTP Android application) password entry as seen here:
![screenshot_20171020_192040-edited](https://user-images.githubusercontent.com/3833277/31834505-74699254-b5ce-11e7-96e3-457118e28ebb.png)

I have not set a URL parameter in any of those two password entry as seen here:
![screenshot_20171020_191943-edited](https://user-images.githubusercontent.com/3833277/31834534-8c460d4e-b5ce-11e7-8b82-6513c8b6678f.png)
![screenshot_20171020_192014-edited](https://user-images.githubusercontent.com/3833277/31834541-90829a12-b5ce-11e7-9b0b-988d8a7250f6.png)

Do you know why would this happen? Do you think the bug comes from your extension or do I need to report this to the KeePassHTTP or KeePassXC project?

Thank your for your time and your extension!

**Comment by PlqnctoN** [comment]
Ok it does the same on my mail provider web interface:
![screenshot_20171020_205013-edited](https://user-images.githubusercontent.com/3833277/31837261-7503e124-b5d8-11e7-9481-93c860d23c3b.png)
Also I forgot to add more details about the versions of software that I'm using so here it is:
KeePassHttp-Connector 1.0.3
KeePassXC 2.2.1
KeePassHTTP 1.8.4.2
Firefox 56.0.1 64bit on Arch Linux

**Comment by smorks** [comment]
hmmm i'll try and do some investigation into why this is happening.

**Comment by smorks** [comment]
this appears to be specific to KeePassXC. it doesn't happen when using just KeePass + KeePassHttp. i believe they are doing the matching slightly different in KeePassXC.

from the bit of testing i did, it looks like it was matching the ".com" part of the windows10forums.com url, to the .com in your @kolabnow.com username.

i'll do some more testing and i'll open an issue in KeePassXC with some more details.

**Comment by smorks** [comment]
looks like it'll be fixed in the next version of KeePassXC: keepassxreboot/keepassxc#1080

**Comment by PlqnctoN** [comment]
I'm sorry I should've done more research before posting this bugreport, thank for your help!
