### ISSUE TITLE
Connector stopped working in FF Quantum 57-beta10

### ISSUE THREAD

**Issue by r0ckarong** [smorks/keepasshttp-connector#28]
I updated to Firefox 57 Developer Edition Beta 10 the other day. 
On the same day I updated to KeepassXC 2.2.2.

The connector stopped working even though my settings have not changed. I can see the extension icon just fine but it is not connected.

Obviously this breaks the Browser Integration, no suggestions or Auto-Fills are performed.

On clicking the extension icon a message tells me:

```
KeePassHttp-Connector has been disconnected from KeePassHttp.
Press the reconnect button to establish a new connection.
```

When I click Reconnect nothing happens. I have purged and recreated the encryption keys in the database and connected a new key to the Extension but the same effect. The Settings dialog shows a connected database but it doesn't work properly.

I'm using:

macOS 10.13
Firefox 57-beta10
KeePassXC 2.2.2
KeePassHttp-Connector Version: 1.0.3
KeePassHttp Version: 1.8.4.2

Connection is on `localhost` with Port 19455 (Default settings).

Are there any log files that I can look at to further define this problem?

**Comment by smorks** [comment]
Make sure the KeePassHttp server is Enabled in the KeePassXC options, and try closing KeePassXC completely, and re-opening.

You can also try remove the KeePassHttp-Connector extension then re-adding it.

**Comment by r0ckarong** [comment]
I removed the connector and re-added it and also restarted KPXC again. Now it works. Weird.

Sorry to bother you.
