### ISSUE TITLE
XML not properly displayed

### ISSUE THREAD

**Issue by kkum** [smorks/keepasshttp-connector#32]
When browsing a xml file the formatted display of the file is not activated for instance http://www.xmlfiles.com/examples/plant_catalog.xml
displays unformmatted, when extension is disable firefox formatting is present

**Comment by varjolintu** [comment]
@smorks I have the same issue. This is Firefox only. It seems adding `	"exclude_matches": [ "*://*/*.xml" ],` to `context_scripts` in manifest.json solves the issue.

**Comment by kkum** [comment]
@varjolintu @smorks Thanks for solving this.
I still have the issue because the page i need to load does not have the xml extension.
Will there be a way to add urls from the options in these exclude_matches list?

**Comment by smorks** [comment]
there currently isn't a way to do that dynamically, as far as i can tell. i'll do some research to see if there's anything else we can do to so you can somehow get it to display xml pages correctly.

**Comment by z3ntu** [comment]
Could you please also ignore .xsd files?

**Comment by z3ntu** [comment]
@smorks Do you know what the root cause of this issue is? Because at least uBlock Origin adds their own .js to every page and it doesn't result in this issue...

**Comment by smorks** [comment]
i'll take a look at the uBlock Origin project and see if I can figure out why they are acting different.

**Comment by varjolintu** [comment]
This is definitely related to jQuery. Removing it from the manifest.json everything works just fine. Need to do more testing. uBlock Origin injects .js to pages but does not use jQuery.
