### ISSUE TITLE
Thunderbird add-on

### ISSUE THREAD

**Issue by gwynpath** [smorks/keepasshttp-connector#33]
It would be nice to have an add-on also for Thunderbird.

**Comment by aptanet** [comment]
I'd been thinking this myself. Having switched from KeeFox for Firefox I'm in need of something for Thunderbird to connect via HTTP rather than RPC.

**Comment by smorks** [comment]
sorry, i'm failing to understand how that would be useful? can you explain to me how this would work with thunderbird?

**Comment by gwynpath** [comment]
In Thunderbird I used to use the same add-on I used with Firefox, which 
is KeeFox.

It works exactly the same as its Firefox counterpart.

**Comment by aptanet** [comment]
Yes, it either pre-fills the password for the account, or has a button to start KeeFox if it isn't already running. I think the addon system is similar to Firefox, but it may be closer to the old system than the new one. I was contemplating trying to manually install ChromeIPass on the basis that a non- updated version may work. There only seems to be KeeFox in the official addons, so nothing that will work with KeePassXC and an http connection unfortunately.

**Comment by smorks** [comment]
it looks like Thunderbird is still using the old-style add-ons. i'm going to close this until it's actually do-able.
