### ISSUE TITLE
Extension was disabled in AMO because it is using an old version of jquery

### ISSUE THREAD

**Issue by smorks** [smorks/keepasshttp-connector#34]
it appears that upgrading to the latest version of jquery isn't easy, because it's basically a customized version using a specific name, i'm assuming to avoid conflicts. it also uses jquery-ui with customizations.

i've been working on updating KeePassHttp to be compatible with the work @varjolintu has been doing in https://github.com/varjolintu/keepassxc-browser, you can see my progress so far here:

smorks/keepasshttp#1

I hope to have it ready in the next few weeks.

to be clear, i plan on discontinuing update on the extension, and help out with varjolintu's, which already has many features which this does not.

**Comment by PlqnctoN** [comment]
> i've been working on updating KeePassHttp to be compatible with the work @varjolintu has been doing in https://github.com/varjolintu/keepassxc-browser, you can see my progress so far here:

Just a quick question regarding this, I don't really understand the overall goal. You are working on a fork of KeePassHttp to make it work with keepassxc-browser while varjolintu has already a fork of KeePassXC compatible with his browser extension? So the goal would either to use your version of KeePassHttp in KeePassXC or to merge the changes made by varjolintu on his KeePassXC fork in the main project?

**Comment by smorks** [comment]
sorry - i should have been more clear. i'm working on the KeePassHttp plugin for KeePass (not KeePassXC), and getting that compatible with varjolintu's browser plugin.

**Comment by smorks** [comment]
turns out it was easier than i originally thought to update the libraries. it should be back on AMO now.
