### ISSUE TITLE
Firefox saves passwords in its own wallet

### ISSUE THREAD

**Issue by gyuris** [smorks/keepasshttp-connector#37]
Previously I used PassIFox with Firefox 56 and KeePassXC. With Firefox 57 I switched to KeePassHttp-Connector. I have many stored passwords in KeePassXC. I have some issues:
1. When I login somewhere with stored password I get "Store credentials" dialog in Firefox as if do not have stored previously the credentials.
2. And if I click on "Yes, store my credentials", they will store in Firefox internally. 
3. If I try to save a new credentials, they are stored only in Firefox and not in KeePassXC wallet.

KeePassHTTP-Connector version: 1.0.5
Google Chrome or Firefox version: Firefox 57 (Ubuntu)
KeePassHttp version: 1.8.4.2
KeePassXC version: 2.2.2

**Comment by smorks** [comment]
with the new Web Extensions, there's no way to use the built in Firefox password manager, so you can just ignore those prompts, or disable it (Options → Privacy & Security → Remembers Logins and Passwords).

**Comment by M3t0r** [comment]
Do you know if Mozilla plans to add this API to web extensions or a place where we could advocate for this? This really made my life a whole lot simpler.

**Comment by SirLupus** [comment]
How do we save new passwords then? Manually in Keepass? 

SaveInCloud is still able to save logindata in their database. Should be possible then to save passwords in KeePass, too?

**Comment by smorks** [comment]
@M3t0r i tried a quick google search and couldn't find anything, so i would guess there's currently no plans? i found this [Credential Management API](https://developer.mozilla.org/en-US/docs/Web/API/Credential_Management_API), but it appears to be more for websites to automatically authenticate. maybe there will be a way to hook into it using an extension to automatically add/retrieve credentials from keepass?

@SirLupus yes, you can save to keepass too. when you enter new/updated credentials, and submit the form, the KeePassHttp-Connector icon should flash red, and if you click on it, it will allow you to add/update the entry.

**Comment by SirLupus** [comment]
Weird, it doesn't flash red for me. Maybe because passifox is still installed but deactivated?

**Comment by smorks** [comment]
i don't think have passifox deactivated should make any difference. can you tell me which website(s) you are trying?

**Comment by SirLupus** [comment]
Looks like it's working now. Just removed some old addons and did a restart. Probably restart did the trick.

**Comment by Moilleadoir** [comment]
Good to know you can still do it, but flashing is a big downgrade in functionality from a popup where you could verify the correct details. The Mozilla motto should be “if it ain’t broke; quick smash it!”

**Comment by gyuris** [comment]
@smorks, thanks for your answers!
