### ISSUE TITLE
Extension disconnected from KeepassXC database after Firefox restart

### ISSUE THREAD

**Issue by SebP7669** [smorks/keepasshttp-connector#38]
Hi,
each time I close my Firefox (57.0) window, the keepasshttp-connector extension is disconnected from my KeepassXC database.
I need to connect it again each time I open Firefox again.
If i'm not mistaken, it does not happen with Chromium.

Any idea on this ?

**My environment:**
Keepasshttp-connector 1.0.6
Firefox 57.0
KeepassXC 2.2.2
xUbuntu 17.10

Thanks a lot
Best regards

**Comment by bungalone** [comment]
The same problem.

Ubuntu 16.04 LTS
Firefox 57.0 developer version
Keepasshttp-connector 1.0.6
KeePassHttp 1.8.4.2
KeePass 2.35

**Comment by smorks** [comment]
hmm, very strange, i've never heard of that before. do you have any settings that may affect this, like maybe stuff that always sets firefox to private browsing mode, or anything along those lines?

**Comment by SebP7669** [comment]
Hi,
no private browsing for me, and no personal data deletion on window close.
But I have other extensions of course such as uBlock and Cookie Autodelete.
May they have an impact ?

Thks

**Comment by smorks** [comment]
try temporarily disabling them and see if that makes a difference?

**Comment by SebP7669** [comment]
OK, I started with a fresh install of Firefox 57.0, without any extension except yours.
Then I re-installed all my extensions, one by one, with a restart of Firefox between each install to see which extension caused the issue.

But the problem disappeared...
If anyone else can make such a test too, i'd be interested in the result.
Thanks a lot
