### ISSUE TITLE
Cannot delete "Specified credential fields" entry

### ISSUE THREAD

**Issue by haarp** [smorks/keepasshttp-connector#39]
Hello,

I'm using 1.0.6 on Firefox 57. When I try to delete a "Specified credential fields" entry, the page is grayed out. I'm expecting some sort of confirmation dialog, but none is visible.

Additionally, I would like to propose not storing these fields in the first place, if they equal the autodetected ones.

**Comment by smorks** [comment]
appears to be a bug, i'm looking into it, thanks!

**Comment by haarp** [comment]
This was fast. Thanks!

**Comment by smorks** [comment]
i should have another release out later today, that has this fix in it.
