### ISSUE TITLE
HTTP Auth dialogs do not work with multiple credentials specified

### ISSUE THREAD

**Issue by haarp** [smorks/keepasshttp-connector#41]
Nothing is filled out, nor do there appear to be any options available while the auth dialog is visible.

**Comment by smorks** [comment]
i just tested, and it appears to work for me. can you give me some examples of websites where it's not working?

**Comment by haarp** [comment]
Unfortunately, I can't. It's a non-public site. It's using Apache2 and "AuthType basic", "require valid-user", so nothing fancy.

When navigating to this site, I only get Firefox's Auth prompt. Even after manually adding an entry for the site to the database, I do not get anything but the prompt. While the prompt is open, the extension's button is inactive and right-clicking on the fields of the prompt does not reveal any password-related options either.

**Comment by smorks** [comment]
try adding an entry for this page, and see if it works for you?

https://auth-demo.aerobatic.io/

**Comment by haarp** [comment]
Same on this site. The connector does not react at all.

What is supposed to be happening?

**Comment by smorks** [comment]
as long as you have an entry with a matching url and correct username/password, the dialog shouldn't pop up at all.

i'm assuming you have the option turned on (Auto fill HTTP Auth dialogs and send them)? i believe it's on by default.

**Comment by haarp** [comment]
Yes, that option is enabled. Could the problem be that I have multiple password entries for this domain?

I noticed something. When the auth prompt appears, a white-on-read question mark becomes visible on the extension's icon. It disappears when I cancel the auth prompt.

However, when I cancel the auth prompt and click on the icon before the question mark disappears, I am offered a list of passwords. If I select the right one and then refresh the page, I am logged in.

**Comment by smorks** [comment]
hmmm, that might be part of the problem. i'll do some testing with multiple entries to see if i can duplicate the problem.

**Comment by smorks** [comment]
i've been able to duplicate the problem, seems to only happen when you have multiple entries.

**Comment by smorks** [comment]
i believe i've fixed it, it now tries all matching credentials until one works. d90a1538193b28967c15226567287c64ed1f4241

**Comment by haarp** [comment]
Thanks! But is

> it now tries all matching credentials until one works. 

wise? If the connection is not using HTTPS, anyone watching traffic could see passwords for multiple accounts instead of just one. Server operators might be able to see all usernames and passwords stored by an user Lastly, it could cause a login for a user/pass combo the user did not want.

**Comment by smorks** [comment]
i was thinking about that too, after i did it, and i don't think it's the best choice either. i will see what i can do about prompting the user to pick credentials, instead of trying all of them.

**Comment by haarp** [comment]
Hey, this works. Thanks a lot!

One last thing. Can you make the extension open itself automatically? I don't mind, but other users might be confused as to why the site doesn't load while the extension is waiting to be clicked on.

**Comment by smorks** [comment]
> One last thing. Can you make the extension open itself automatically? I don't mind, but other users might be confused as to why the site doesn't load while the extension is waiting to be clicked on.

i don't believe there's an easy way to do this. i will have to investigate some more though.

i will update the settings page. i'm thinking it might be better to give an option to work the way it used to (to try the first given credentials) or just to do what it's doing now, if multiple credentials are found.
