### ISSUE TITLE
Add-on fails to auto-fill credentials for protonmail

### ISSUE THREAD

**Issue by Mcinwwl** [smorks/keepasshttp-connector#43]
Hi, and thanks for porting the thin to FF 57 - PassIFox was a must-have for me for a last year or two :> 

However, now add-on fails to auto-fill credentials on protonmail.com. It just... doesn't. I am Protonmail user since beta, and I still have two-password login. I use two entries, one for protonmail.com itself, and one for https://mail.protonmail.com/login/unlock. When I click icon and try to choose credentials from the list proposed, they ain't appearing. Only right-clicking on the login field works.

To make it more funny, on unlock page, only addon-icon option works, as right clicking on password field and right click does nothing. Needless to say, that that this combination worked with original pfn's addon.

Windows 7x64 pl here, FF 57.0 pl, other add-ons are uBlock Origin and S3.Translator. In case more data is needed, I'm glad to help.

**Comment by smorks** [comment]
this appears to be the same issue as #12. i'll add protonmail to list of sites to test with. when the username & password fields are dynamically loaded, then it doesn't find them. i suggest using Ctrl+Shift+U for now.
