### ISSUE TITLE
Can't connect  anymore to sites using http authentication

### ISSUE THREAD

**Issue by yennor** [smorks/keepasshttp-connector#44]
Since the new version which got installed here on the 22.11.2017 I can't open any pages anymore which use http authentication. (The kind of authentication where firefox opens a pop up and asks you to enter your credentials, which for example the tomcat manager uses).
Firefox just seems to load forever...
When I disable the plugin, everything works again (took me forever to find out that it wasn't a server problem...)

**Comment by smorks** [comment]
sorry, i changed the way http auth works, when there are multiple credentials that match. you need to click on the KeePassHttp-Connector icon, then select the specified credentials you want to use to login.

i may end up adding an option to make it either work the way it used to work (returning the first found credential) or this new way.

**Comment by yennor** [comment]
I've just tried that out.
There is nothing when I click on the icon. It only shows me the options for redetecting credential fields.
Firefox just continues to load the page forever and nothing happens, also not with the icon.
I had to go to the settings, and deactivate:
"Auto fill HTTP Auth dialogs and send them. "
Now when I click on the Icon, it shows the credentials. But it's really really akward like that (most people will not notice that and just think the page doesn't load).

**Comment by smorks** [comment]
oh - so you're saying that you don't have any credentials saved for the site? i will have a look at that then, thanks!

**Comment by yennor** [comment]
There are actually two bugs:
if "Auto fill HTTP Auth dialogs and send them. " is activated, nothing works at all.
If you deactivate it and you've got credentials you can get them over the icon (IF you know about that).
If you've got no credentials for that page, then it's the same. you can't enter new ones.
It0s actually the same problem. If there are already credentials for that domain, but not the correct ones yet, you can not enter new ones.

**Comment by smorks** [comment]
i'm not seeing the same behavior. here is what is happening for me:

with "Auto fill HTTP Auth dialogs and send them" turned ON:

- if i have no credentials for the site, it prompts for a username & password.
- if i have one set of credentials, it uses them and works
- if i have multiple, i have to click on the icon and select one
- if the one i selected isn't correct, i get prompted for a username & password

with "Auto fill HTTP Auth dialogs and send them" turned OFF:

- if i have no credentials for the site, it prompts for a username & password.
- if i have one or more credentials, i have to click the icon and select one
- if the one i selected isn't correct, i get prompted for a username & password

can you tell me what browser & operation system that you are using? and if possible, what site you're trying to authenticate at?

**Comment by yennor** [comment]
firefox 56
debian linux stretch (stable)
I'm trying to authenticate against the management console of a tomcat. (I prefer not to publish the URL in a public forum, but it doesn't work with any of them, not tomcat 7 nor tomcat 8)

**Comment by yennor** [comment]
Well as I said above, it works if "Auto fill HTTP Auth dialogs and send them" is deactivated and there are already credentials.

**Comment by smorks** [comment]
so you're saying you're not seeing the same behavior that i have listed above?

can you try and test on this page: https://auth-demo.aerobatic.io/ with the "Standard Auth" button?

**Comment by yennor** [comment]
ok that page was a pretty bad example, I had to close and open the
browser after each login since it doesn't properly log me out ;-).

anyway:
"Auto fill HTTP Auth dialogs and send them." off
- Asks me for credentials, but does NOT offer me to store them in
Keepass, I had to create an entry manually to do the other tests.
- after entering credentials manually, it asks me for the credentials
(after clicking on the icon)

"Auto fill HTTP Auth dialogs and send them." on
- when having no credential: asks me for credential, but doesn't offer
to store them.
- when having one credential: it doesn't auto log in, but I can choose
the credential.

So it seems like it works with that page, besides that I can't save the
credentials.

What I've also noticed, if you enter the url to load, then you change to
another tab, since you don't want to wait until the page is loaded (what
I never do), and then you come back to the previous tab, the icon
doesn't show the possible logins anymore, it's just in endless page
loading mode again. (another bug :-))

If you want to I can send you a private message with an URL where we've
got a test installation of Tomcat instance. I can't give you any
credentials, but you can see, how firefox just loads the page forever
and never ask for credentials, also nothing happening with the icon... I
guess you could analyze the traffic to see what is send...

**Comment by smorks** [comment]
yes, there's nothing i can do about saving new credentials for http auth, i don't believe there's a way for the extension to access them once they've been entered manually.

and sure, go ahead and send me the url privately.

**Comment by yennor** [comment]
I'm using KeePassXC 2.2.2

Really strange. For me the url never prompts for a password. but the other url you've send me does. 
You think the problem could be related to the keepasshttp implementation?

(I've just returned the conversation to github, maybe somebody else has got the same problem and could jump in with more details :-))

> So I ran a few tests using your URL with the "Auto fill HTTP Auth dialogs and send them" option ON, and everything appeared to behave normally.
> 
> When I had no credentials entered, it prompted.
> When I had one set (incorrect, of course), it tried them, then prompted because they were incorrect.
> When I had multiple, I had to select from the icon, then it prompted because they were incorrect.
> 
> Just curious, are you using KeePass or KeePassXC?
> 
>

**Comment by smorks** [comment]
just to be sure, i tested with KeePassXC 2.2.2, and it worked for me as well.

i'm also going to test with your version of linux (debian stretch) and firefox 56 too, since i've been doing all my testing on windows and firefox developer edition (v58).

**Comment by yennor** [comment]
wow. you really put effort into that. :-)
Tell me if I can help in any way.
Getting some debug logs or something.

**Comment by smorks** [comment]
ok, i'm confused. i tested with on debian with KeePassXC 2.2.2, and firefox 56, and everything seemed to work normally. there must be something else going on here.

maybe try testing with a new firefox profile? or re-installing the add-on?

**Comment by yennor** [comment]
I created a new profile: et voila.
now it works as you say...
argh, so maybe an other add on is the problem, or just something is
messed up in the profile...
later in the evening I will try out to disable some add ons...

**Comment by smorks** [comment]
i'm going to close this issue. if you find it was a particular add on, let me know, and maybe there's some way i could work around it in the future. thanks!
