### ISSUE TITLE
contact Firefox / Chrome developers to fix / improve WebExtensions API

### ISSUE THREAD

**Issue by adrelanos** [smorks/keepasshttp-connector#48]
https://github.com/smorks/keepasshttp-connector/issues/46#issuecomment-346847247

> With the WebExtensions API, we are not able to tie in to the functionality of the build-in password manager in Firefox.

> I know that PassIFox was a more seamless experience, but due to limitations in the API, this extension is missing some of that functionality.

Could you please open a bug / feature request against Firefox / Chrome explaining this issue so WebExtensions API gets improved so we can get back to the PassIFox more seamless experience?

**Comment by smorks** [comment]
I believe users should use the built-in feedback options in their browsers to request this feature.

**Comment by adrelanos** [comment]
Firefox bug report:

https://bugzilla.mozilla.org/show_bug.cgi?id=1324919
