### ISSUE TITLE
Shortcuts to fill username/password not working in chromium

### ISSUE THREAD

**Issue by MasseElch** [smorks/keepasshttp-connector#51]
Neither the default nor custom shortcuts are working when using the extension with chromium. 

![image](https://user-images.githubusercontent.com/12862103/33595336-f117327e-d997-11e7-8f7d-2832d084f9a3.png)

![image](https://user-images.githubusercontent.com/12862103/33595349-00f9e88a-d998-11e7-873f-c2e0b56139a2.png)

**Comment by smorks** [comment]
very strange. i tested on Chrome & Chromium, and only Chromium doesn't seem to be working. will look into it some more.

**Comment by grimpy** [comment]
Does not work for me either on firefox 57 (linux) and the link to change these shortcuts doesnt seem correct for firefox `chrome://extensions/configureCommands`

ctrl+shift+u just gives me a u with underscore under it

**Comment by smorks** [comment]
i don't believe there's currently a way to change the shortcuts in firefox, only chrome.

i will test with firefox on linux to see if i can reproduce what you're seeing, @grimpy.

**Comment by z3ntu** [comment]
Yeah ctrl+shift+u is for entering unicode characters on linux. eg ctrl+shift+u and then typing 1234 and enter gives me ሴ

**Comment by smorks** [comment]
@MasseElch it appears shortcut keys are working in chromium again, i tested with version 63.0.3239.108 and it worked for me, in both Windows and Linux.

I think i'll change the Username & Password shortcut key to Alt+Shift+U, which in a quick test worked fine for me in Linux. that way both shortcut keys will be Alt+Shift+<Key>, which is at least a little more consistent.

**Comment by MasseElch** [comment]
Im on Version 63.0.3239.108 (Developer Build) (64-bit) now but it still is not working.

I tried to use global shortcuts instead of chrome ones (when visiting `chrome://extensions/configureCommands) and it had no effect. 

Changed to Alt+Shift+U and it did not work.

Im on Mac though. It might be a problem with MacOS then?

**Comment by smorks** [comment]
i will try and do some testing on a mac tonight and i'll let you know what i find.

**Comment by MasseElch** [comment]
@smorks Thank you very much 👍

**Comment by janhicken** [comment]
I can confirm that the URL [chrome://extensions/configureCommands](chrome://extensions/configureCommands) does not work in Firefox 57.0.3

**Comment by ramenchef** [comment]
Chrome Version 63.0.3239.132 (Official Build) (64-bit) Windows 10 Pro 64bit. I cannot get any shortcuts to work with this extension. Setting the shortcut to global does not fix the issue either. I have tried multiple different bindings including ctrl+0, ctrl+9, ctrl+p, etc.

**Comment by ligyxy** [comment]
Same issue. Chrome Version 64.0.3282.119 (Official Build) (64-bit), Mac OS 10.13.3
The shortcut doesn't work even if I change it to some other combinations. Same shortcut setting works for chromeIPass, so I think it should not be the key combination issue.

**Comment by masseelch** [comment]
@smorks Any progress on this?

**Comment by smorks** [comment]
sorry, i don't own a mac, so it's difficult for me to properly test this. also, I'm no longer maintaining this extension, as noted on the main page of this repo, since there are more secure alternatives available.
