### ISSUE TITLE
HTTP Auth login not working on at least one site - have drawn a blank so far...

### ISSUE THREAD

**Issue by agsteele** [smorks/keepasshttp-connector#54]
I've noted a number of threads re the HTTP auth login using the KeepassHTTP-connector.  My issue may well be a similar issue to one these others but I'm uncertain. I'll post the observations here and trust that if they relate to another open thread that they will be merged.

I have a small subset of pages on a website which sit in a single directory. To protect the data that sits behind those pages we have used a simple HTTP Auth login which used to work just fine with IPassFox. Now the HTTP Auth login box pops up and can be completed manually. This login always works. But the automatic completion of the login by the Connector add-on does not work. 

I've tried this with the 'Auto fill HTTP Auth dialogs and send them' flag both checked and unchecked.

I tested at the https://auth-demo.aerobatic.io/ site which seemed to work OK. However, I've had several http-auth logins not work but I've not given them attention until now.  I have a sense that there is something inconsistent which affects some http-auth logins and not others.

I've attached the htaccess file for this web directory (replacing the actual directory which gives away the domain with my.domain. Otherwise it is the same content.

[htaccess.txt](https://github.com/smorks/keepasshttp-connector/files/1534362/htaccess.txt)

KeePassHttp-Connector Version: 1.0.8
KeePassHttp Version: 1.8.4.2
Firefox 57 (64-bit)
Windows 10

**Comment by smorks** [comment]
see my comment here: https://github.com/smorks/keepasshttp-connector/issues/53#issuecomment-349718304

**Comment by agsteele** [comment]
Thanks for the response in #53.  I had checked #41 and wondered whether it was caused by multiple credentials.  However, when the HTTP Auth login box opens the Connector icon is not clickable. I just get an error ping.  I then ensured that only one username and password was being used on this domain and the login still fails.

**Comment by smorks** [comment]
ok, if you are just getting the HTTP Auth popup, then it sounds like the same as #9.

the way it is supposed to work is the popup shouldn't show at all, and it should just authenticate you with the site.

i will try and test with the same .htaccess you provided and see if i can reproduce the problem.

**Comment by agsteele** [comment]
If it would assist I can create a login for you.  I'm currently running a dummy index page so no live content. Give me a way to communicate privately and I'll do the necessary.

**Comment by agsteele** [comment]
Add-On debug logging when attempting to log-in to the problem domain with HTTP Auth.  

The first few lines in the log were, I think, generated before I attempted the HTTP Auth but there are some lines which suggest errors after the GET command.  I've obscured the domain but made no other changes.

[debug_log.txt](https://github.com/smorks/keepasshttp-connector/files/1536354/debug_log.txt)

**Comment by smorks** [comment]
there isn't a whole lot in the log that really helps. i do see a `[HTTP/1.1 401 Unauthorized 134ms]`, which may mean that it tried to authenticate but wasn't successful.

you can contact my privately at my e-mail address listed on my github profile.

**Comment by smorks** [comment]
i tested, and everything worked as expected for me. once i entered the credentials in keepass, i visited the page, there was a popup for me to allow or deny access (it's a keepass window and sometimes the window doesn't always come to the front), and once i hit allow, it worked.

**Comment by agsteele** [comment]
Thanks for your persistent assistance.

The KeePass access confirmation isn't an issue as far as I can tell. There must be some configuration difference between your setup and mine.  I took the default settings in the Connector add-on so perhaps you and I have some subtle difference in our Firefox config.  Decades of adjusting Firefox to do just what I want with even a few about:config tweaks could be the problem too.

For now this is an issue which is not resolved.  I'm not sure that I have time right now to make a clean install of Firefox to see what happens but I'll try to do that over the Christmas weeks if not before and report back.

**Comment by smorks** [comment]
you can also try just creating a new profile in firefox, that way you shouldn't lose anything in your existing profile.

http://kb.mozillazine.org/Creating_a_new_Firefox_profile_on_Windows

**Comment by agsteele** [comment]
Great suggestion which resolved the issue.  So a clean Firefox installation works just fine.  When I'm needing a break from proper work I'll try tweaking Firefox to see if I can get the issue to resolve.

I'll report back.

**Comment by smorks** [comment]
it could be other add-ons too that may be interfering. let me know if you figure it out. i'll close this issue for now.

**Comment by agsteele** [comment]
Thanks Andy. Not other add-ons. I disabled all except the Connector and got the same issue.
