### ISSUE TITLE
Basic Authentication not workin anymore with Version 1.0.9

### ISSUE THREAD

**Issue by MBurchard** [smorks/keepasshttp-connector#56]
Today I tried to connect to the Tomcat Manager application that uses basic authentication.
Instead of being able to select the appropriate credentials from the KeePassHTTP-Connector symbol as before, I get the browser dialogue in which I have to enter the data manually...

**Comment by smorks** [comment]
can you give some details of your environment (os version, browser version, keepass/keepassxc version).

did you double-check that the Auto-Fill HTTP Auth Dialogs option is checked?

**Comment by MBurchard** [comment]
As I said... same days ago it worked and I haven't changed my system.

- Windows 10
- Firefox 57.0.2
- KeePassHttp-Connector 1.0.9
- KeePassXC 2.2.2 and 2.2.4
- Auto fill HTTP Auth dialogues and send them **is not checked**

And was not checked, because I have different credentials for the same URL, witch is http://localhost:7070/manager/html. It is a tunnelled connection to a lot of different remote Tomcat Installations, with different credentials.
Two or three days ago, I was able to click on the KeePassHTTP-Connector Icon in the browser bar and chose the correct credentials. This functionality is gone...

**Comment by smorks** [comment]
yes, that option needs to be checked now. if you have multiple credentials for the same site, you will need to click on the extension icon then select the credentials you want to use.

**Comment by MBurchard** [comment]
Interesting... why was this change done?
So adding new credentials is only possible, if done in KeePassXC now?

**Comment by smorks** [comment]
The option really wasn't doing anything before, regardless if it was checked or not. it was still auto-filling in the auth dialog if you had multiple credentials and selected one from the icon. i was hoping it is clearer now.

adding new credentials through HTTP Auth was never possible, at least through the Web Extension add-on.

**Comment by MBurchard** [comment]
Thank you for clarification and quick response...
