### ISSUE TITLE
Clean up license

### ISSUE THREAD

**Issue by rugk** [smorks/keepasshttp-connector#59]
The license here is kinda messy…

So first the Markdown in the `LICENSE.md` file goes crazy. If you are lazy, just put everything into a big code block or just rename it to TXT, but currently it looks strange.

Also there is some GPL stub at the end of the Readme. This is also not where it belongs to. That should be moved into the source code in a comment at the top or so. Currently, without any formatting, it just looks as if one accidentally put that thing under the (unrelated) m"Troubleshooting" headline.

**Comment by z3ntu** [comment]
A markdown version of the GPLv3 is available at https://www.gnu.org/licenses/gpl-3.0.md .
