### ISSUE TITLE
 KeePassHttp-Connector has encountered an error:  Unable to connect to KeePassHttp 

### ISSUE THREAD

**Issue by blacky68** [smorks/keepasshttp-connector#65]
Hello,

I get always following error message with the KeePassHttp-Connector Add-on Version:
1.0.9 and Firefox 57.0.1

" KeePassHttp-Connector has encountered an error:
Unable to connect to KeePassHttp "

I have tried the following steps to fix this problem without any success:

- deleted the KeePassHttp Settings entry in the KeePass DB
- deleted the connected databases in the KeePassHttp-Connector Add-on Settings
- I have tried try to create a new databases connection in the KeePassHttp-Connector Add-on but nothings happes, no popup is comming where I can put in the name for this Connection
- I have reinstalled the KeePassHttp plugin in the KeePass2 folder
- restart the Firefox and Linux after the different changes

I use the same KeePass database with the KeePass in Windows 10 with Firefox and the KeePassHttp-Connector Add-on without any problems. 

So, my question is now. What can I do in the best way to fix this problem in Linux or how can I get more Information in any logfile to understand this error?

Many Thanks.

**Comment by smorks** [comment]
maybe try creating a new profile in firefox and see if that works? sometimes other extensions can interfere.

i think the instructions are greated towards windows but i believe it should work on linux too: https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by blacky68** [comment]
Thanks for the fast answer.

That is of course a good Idea and I tested it immediately but it did dosn't work. I get the same error message as before.

**Comment by smorks** [comment]
you can try to go here in firefox: about:debugging#addons

then you find KeePassHttp-Connector, then click on the "Debug" link below. it should bring up a dialog which you should Allow, then you should able to see various errors and info in the "Console" tab.

**Comment by blacky68** [comment]
Thanks, I don't know what it's happen but now it works again. I have started the debuging mode like your description and then I could connect the database again. I hope it will works now permanently and if not I will post here again ;-)

Many Thanks for your help.
