### ISSUE TITLE
Support for more than just username and password fields. 

### ISSUE THREAD

**Issue by Throdne** [smorks/keepasshttp-connector#66]
There are several sites I use that has a third field beyond just the standard username and password. sometimes called passphrase, account, etc. I would like to save those fields along with username and passwords. Maybe use String Fields for additional fields.

**Comment by smorks** [comment]
i believe this should already be possible, see here: 

https://github.com/smorks/keepasshttp-connector/blob/master/documentation/KeePassHttp-Connector.md#37-fill-in-additional-values-via-string-fields
