### ISSUE TITLE
New credentials are saved in Firefox not in Keepass

### ISSUE THREAD

**Issue by MarcSN311** [smorks/keepasshttp-connector#67]
When saving a Login it is saved to the Firefox password Database, not to Keepass.

KeePassHttp-Connector Version: 1.0.9
KeePassHttp Version: 1.8.4.2
Firefox Version: 56.0.2 (64-bit)

**Comment by z3ntu** [comment]
You have to click the blinking plugin icon after entering new credentials.

**Comment by smorks** [comment]
see #37, #45.
