### ISSUE TITLE
Feature Request - Store existing browser login and password information not already in KeePassXC

### ISSUE THREAD

**Issue by phd21** [smorks/keepasshttp-connector#68]
Hi smorks, Andy Brandt, etc...

First, thank you for this excellent add-on extension. 

Feature Request -  Store (add) existing browser login and password information not already in KeePassXC database. 

While in Firefox 57 Quantum, I already have stored logins and passwords, apparently some of which were not in my KeePassXC database. It would be awesome in any browser to have "keepasshttp-connector" or KeePassXC automatically detect that a wesbite login was not in KeePass but stored in the browser and automatically save it (or ask) to my KeePass database. It would be really nice to do that with the entire browser's stored logins and passwords, like an import option.  Especially since Firefox 57 no longer has an option to export passwords, but this would be a great option for all browsers.

I am currently using Linux Mint KDE 18.2 based on Ubuntu 16.04 and Linux Mint KDE 17.3 based on Ubuntu 14.04 with current browsers Firefox 57, Slimjet, Chrome, Opera, Brave, etc... with current versions of KeePassXC and "keepasshttp-connector".

Thanks!

Best regards to you and yours,
Phil
phd21

**Comment by smorks** [comment]
there is currently no way for the new WebExtensions to access the credentials stored in firefox, so there would be no way to do an import.

when you do login to a site, if the credentials are filled in by firefox, and then you login, then you should be able to save the credentials to KeePassXC by clicking on the flashing red KeePassHttp-Connector icon.
