### ISSUE TITLE
Force storing credentials to KeePass

### ISSUE THREAD

**Issue by woj-tek** [smorks/keepasshttp-connector#69]
I have lot's of passwords already stored in Firefox. If I understand the mechanism of detecting/storing passwords correctly - KeePassHttp-connector will only detect those if they are not already stored in the browser.

It would be nice to have an option to force detecting and storing those passwords always (or at least if the same domain/username is not already stored -- but then again there may be a case of updating passwords)

**Comment by smorks** [comment]
KeePassHttp-Connector has no way to access credentials stored in Firefox's built-in password manager, so it should be using any credentials, regardless if they're stored in Firefox.

**Comment by woj-tek** [comment]
Hmm, then this is a more general problem of "not detecting credentials in some circumstances" then, so this issue can be closed because there are already others that cover this.
