### ISSUE TITLE
v1.0.9 not tagged/on GitHub

### ISSUE THREAD

**Issue by rugk** [smorks/keepasshttp-connector#74]
The current add-on version on AMO is 1.0.9. The [current one](https://github.com/smorks/keepasshttp-connector/releases) on GitHub is 1.0.8.

**Comment by z3ntu** [comment]
v1.0.9 is commit https://github.com/smorks/keepasshttp-connector/commit/e1c002461caed4b9656cd4f9e87d87729d64a905
v1.0.10 is commit https://github.com/smorks/keepasshttp-connector/commit/7d8fe3812d3e54bfeeb70cff65b554c820cc515a

**Comment by smorks** [comment]
they've now been tagged. thanks!
