### ISSUE TITLE
Automatically fill-in single credentials entry option stopped working

### ISSUE THREAD

**Issue by slunak** [smorks/keepasshttp-connector#89]
Using:
Chrome 64.0.3282.167 (Official Build) (64-bit) or Firefox 58.0.2 (64-bit), both latest.
KeePassHttp-Connector: 1.0.11
MacPass: Version 0.7.3 (17830)
KeePassHttp: KeePassHTTPKit

Issue:
Usually when single entry is returned, it is automatically is auto typed into the form. I have Automatically fill-in single credentials entry option enabled. About a week ago it stopped auto typing in both Chrome and Firefox browsers at the same time. When clicking on the form, single entry comes up and it is possible to choose it, then it fills the form.

![image](https://user-images.githubusercontent.com/8351121/36490538-60d0554e-1720-11e8-82d2-be2b827bf96a.png)

Additional Information:
I can see that KeePassHttp-Connector was updated to version 1.0.11 a week ago, perhaps this is related?

Where would you advise to look for a solution? Anyone esle with the same issue? Thank you!

**Comment by smorks** [comment]
the default for the Auto Fill Single Credential Entry option was changed to off by default.

so try turning the option off, then on again, and see if that works.

**Comment by slunak** [comment]
Yes, worked. Thank you very much for your help!

**Comment by z3ntu** [comment]
Was the same for me
