### ISSUE TITLE
Prevent websites scraping account data/identifying users

### ISSUE THREAD

**Issue by rugk** [smorks/keepasshttp-connector#90]
See
https://textslashplain.com/2017/12/28/taking-off-your-nametag/

Currently once you allow the extension to retrieve a password, it is retrieved.

**Comment by smorks** [comment]
It sounds like as long as you have the "Auto fill single credentials" option OFF, then it shouldn't be an issue.

Unless i'm understanding the article wrong? I've bolded the relevant text from the article:

> Because users often wish to use the password manager even in while Incognito, the feature isn’t disabled, but instead enters a mode called “Fill on account select” (FOAS) whereby the user must manually select an account from a dropdown in order to fill the username and password. **This helps prevent a site from silently identifying a user.**

**Comment by rugk** [comment]
Ah, there is such an option, then, yes, that's it! Also see https://bugs.chromium.org/p/chromium/issues/detail?id=798492 for other potential mitigations.

**Comment by rugk** [comment]
So?

BTW Chromeium 60 or so implemented that sites cannot read out the password field, unless you interact with the field.
