### ISSUE TITLE
"Auto fill HTTP Auth dialogs and send them" still not shows auth form

### ISSUE THREAD

**Issue by Felixoid** [smorks/keepasshttp-connector#91]
Good ~(morning|afternoon|evening|night)!

When FF try to open pages with basic auth, nothing showed. I'll be glad to give you any necessary info

Firefox: 58.0.2 (64-bit)
KeePassHttp: 1.8.4.2
KeePassXC: 2.2.4

**Comment by smorks** [comment]
have you tried clicking on the KeePassHttp Extesion Icon, to see if there are credentials to select from there?

**Comment by Felixoid** [comment]
It's unavailable because of active BasicAuth window

**Comment by smorks** [comment]
if that dialog is coming up, it may mean any of the following:

1. The "Auto fill HTTP Auth dialog" option is not checked
2. Credentials weren't found for the site
3. Wrong credentials were entered

You can try testing at this auth page:

https://auth.brandt.tech
Username: user
Password: pw1234

**Comment by Felixoid** [comment]
Sorry for long silence.

So, there are results of testing:
Autofill is checked.
* No credentials in keepassxc: form is showed
* Credentials added: https://yadi.sk/d/AbHjbiH73TLh5B. Everything is working

It's not working on another site, so I'm not sure where is a problem, but I'm switched to the KeepassXC-Browser, there everything is fine. I guess you could close this issue as "Not reproduced'

Many thanks in any case! Your plugin saved me half of year ago.
